version: '3.7'
services:
    web-app-a:
        image: web-app
        container_name: web-app-a
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "10000:80"
            - "20000:3306"
        volumes:
            - ./m214-web-app-a:/home/web/web-app

    web-app-b:
        image: web-app
        container_name: web-app-b
#         build:
#             context: .
#             dockerfile: ./Dockerfile
        ports:
            - "10001:80"
            - "20001:3306"
        volumes:
            - ./m214-web-app-b:/home/web/web-app


